spring.application.name=Link-Shortener

spring.datasource.url=jdbc:postgresql://${LINK_SHORTENER_DB_HOST}
spring.datasource.username=${LINK_SHORTENER_DB_USER}
spring.datasource.password=${LINK_SHORTENER_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
